### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by Madhour** [BennerLukas/Cooky#1]
- [ ] Startup Sequence to initiate user profile
- [ ] Stock management -> Barcode, list
- [ ] Start page for searching recipes

**Comment by BennerLukas** [comment]
Following Pages are needed:

- [x] Start Page
- [ ] Manage Stock/ Pantry
- [ ] Explore/ Search Recipe
- [ ] Detail Recipe Page (inkl. rating button)
- [ ] Settings (change user_id)
